name: Jason Oswald
favicon: null
layout_spectrum: 0.8168733278289437
typography_spectrum: 0.7927152724005282
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.40572691336274147
  lightness: 0.8684496048372239
  saturation: 0.09386428608559072
  rhythmicContrast: 0.28767050825990736
purpose: []
